//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWebApplication.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.HelloWebServiceSoap")]
    public interface HelloWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage1", ReplyAction="*")]
        HelloWebApplication.ServiceReference1.GetMessage1Response GetMessage1(HelloWebApplication.ServiceReference1.GetMessage1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessage1", ReplyAction="*")]
        System.Threading.Tasks.Task<HelloWebApplication.ServiceReference1.GetMessage1Response> GetMessage1Async(HelloWebApplication.ServiceReference1.GetMessage1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessage1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessage1", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebApplication.ServiceReference1.GetMessage1RequestBody Body;
        
        public GetMessage1Request() {
        }
        
        public GetMessage1Request(HelloWebApplication.ServiceReference1.GetMessage1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessage1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetMessage1RequestBody() {
        }
        
        public GetMessage1RequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessage1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessage1Response", Namespace="http://tempuri.org/", Order=0)]
        public HelloWebApplication.ServiceReference1.GetMessage1ResponseBody Body;
        
        public GetMessage1Response() {
        }
        
        public GetMessage1Response(HelloWebApplication.ServiceReference1.GetMessage1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessage1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMessage1Result;
        
        public GetMessage1ResponseBody() {
        }
        
        public GetMessage1ResponseBody(string GetMessage1Result) {
            this.GetMessage1Result = GetMessage1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWebServiceSoapChannel : HelloWebApplication.ServiceReference1.HelloWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWebServiceSoapClient : System.ServiceModel.ClientBase<HelloWebApplication.ServiceReference1.HelloWebServiceSoap>, HelloWebApplication.ServiceReference1.HelloWebServiceSoap {
        
        public HelloWebServiceSoapClient() {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HelloWebApplication.ServiceReference1.GetMessage1Response HelloWebApplication.ServiceReference1.HelloWebServiceSoap.GetMessage1(HelloWebApplication.ServiceReference1.GetMessage1Request request) {
            return base.Channel.GetMessage1(request);
        }
        
        public string GetMessage1(string name) {
            HelloWebApplication.ServiceReference1.GetMessage1Request inValue = new HelloWebApplication.ServiceReference1.GetMessage1Request();
            inValue.Body = new HelloWebApplication.ServiceReference1.GetMessage1RequestBody();
            inValue.Body.name = name;
            HelloWebApplication.ServiceReference1.GetMessage1Response retVal = ((HelloWebApplication.ServiceReference1.HelloWebServiceSoap)(this)).GetMessage1(inValue);
            return retVal.Body.GetMessage1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HelloWebApplication.ServiceReference1.GetMessage1Response> HelloWebApplication.ServiceReference1.HelloWebServiceSoap.GetMessage1Async(HelloWebApplication.ServiceReference1.GetMessage1Request request) {
            return base.Channel.GetMessage1Async(request);
        }
        
        public System.Threading.Tasks.Task<HelloWebApplication.ServiceReference1.GetMessage1Response> GetMessage1Async(string name) {
            HelloWebApplication.ServiceReference1.GetMessage1Request inValue = new HelloWebApplication.ServiceReference1.GetMessage1Request();
            inValue.Body = new HelloWebApplication.ServiceReference1.GetMessage1RequestBody();
            inValue.Body.name = name;
            return ((HelloWebApplication.ServiceReference1.HelloWebServiceSoap)(this)).GetMessage1Async(inValue);
        }
    }
}
